/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import facturacion.Estilos;
import facturacion.Facturacion;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.SwingConstants;

/**
 *
 * @author henrypb
 */
public class FrameAccesoPrincipal extends javax.swing.JFrame {

    static JFrame miFrame;
    static JProgressBar miProgressBar;
    
    public FrameAccesoPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBackDoor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnEntrar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setName("FrameBienvenido"); // NOI18N

        lblBackDoor.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblBackDoor.setText("SISTEMA DE FACTURACION");
        lblBackDoor.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblBackDoor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblBackDoor.setOpaque(true);
        lblBackDoor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackDoorMouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bean/utilitario/imagenes/portal_desica01.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 197, 2)));

        jDesktopPane1.setBackground(new java.awt.Color(95, 118, 144));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bean/utilitario/imagenes/llave16px.png"))); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        btnEntrar.setBounds(170, 100, 130, 44);
        jDesktopPane1.add(btnEntrar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField1.setText("facturacion");
        jTextField1.setToolTipText("");
        jTextField1.setBounds(170, 20, 115, 27);
        jDesktopPane1.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel4.setText("Contraseña: ");
        jLabel4.setBounds(60, 60, 94, 17);
        jDesktopPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPasswordField1.setText("facturacion");
        jPasswordField1.setBounds(170, 60, 87, 27);
        jDesktopPane1.add(jPasswordField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel3.setText("Usuario:");
        jLabel3.setBounds(60, 30, 94, 17);
        jDesktopPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBackDoor, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblBackDoor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 95, Short.MAX_VALUE))
        );

        lblBackDoor.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    private static void mostrarFrameBienvenida() {
        JLabel comentarioBienvenida = new JLabel("BIENVENIDO!!", SwingConstants.CENTER);
        comentarioBienvenida.setLocation(130, 70);
        comentarioBienvenida.setSize(220, 40);
        comentarioBienvenida.setFont(new Font("Dialog", 1, 20));
        miProgressBar = new JProgressBar(0, 100);
        miProgressBar.setSize(220, 20);
        miProgressBar.setLocation(130, 100);
        miProgressBar.setBorderPainted(true);
        miProgressBar.setBorder(BorderFactory.createRaisedBevelBorder());
        JPanel contenido = new JPanel(null);
        miFrame = new JFrame("FACTURACION");
        miFrame.setContentPane(contenido);
        miFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //Container contentPane = miReportFrame.getContentPane();
        miFrame.setSize(500, 250);
        miFrame.setLocation(250, 200);
        miFrame.add(comentarioBienvenida);
        miFrame.add(miProgressBar);
        miFrame.setVisible(true);
        try {
            for (Integer i = 0; i <= 200; i += 20) {
                Thread.sleep(i);
                miProgressBar.setValue(i / 2);
            }

        } catch (InterruptedException ex) {
            Logger.getLogger(Facturacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }  // metodo mostrarFrameBienvenida(). 
    
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    private void accederMenuPrincipal() throws Exception {
         this.dispose();
         //JOptionPane.showMessageDialog(this, "Entrar confirmado");
         // ** Estados de Prueba  (Brqto: 09/04/2014):  
         //FrameMenuPrincipalOld frameMenuPrincipal = new FrameMenuPrincipalOld();  // (Ok.)
         //FrameMenuPrincipal frameMenuPrincipal = new FrameMenuPrincipal();        // (Ok.)
         //FrameMenuPrincipalImagen frameMenuPrincipal = new FrameMenuPrincipalImagen(); 
         //**
         //FrameMenuPrincipalAnimado frameMenuPrincipal = new FrameMenuPrincipalAnimado(); 
         // **
         FrameMenuPrincipal frameMenuPrincipal = new FrameMenuPrincipal(); 
         // ** 
         frameMenuPrincipal.setSize(Estilos.xWindow,Estilos.yWindow);
         frameMenuPrincipal.setVisible(true);
    } // accederMenuPrincipal().  
    
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        //JOptionPane.showMessageDialog(this, "Entrar confirmado");
        //accederMenuPrincipal(); 
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void lblBackDoorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackDoorMouseClicked
        try {
            //JOptionPane.showMessageDialog(this, "Entrar via backDOOR");
            accederMenuPrincipal();
        } catch (Exception ex) {
            Logger.getLogger(FrameAccesoPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblBackDoorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAccesoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAccesoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAccesoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAccesoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            /*
             * NOTA al 04-12-2012 a las 14:00. 
             * El @Override, es una annotation. Una annotation es información
             * adicional que se le puede agregar a un método, atributo o clase,
             * para que alguien pueda leerla en otro momento. La annotation
             * Override la lee el eclipse para saber que ese método debe
             * sobrescribir a uno de una clase superior de la jerarquía de
             * herencia. De esta forma, si no ocurre, el código deja de
             * compilar. Pruebe de cambiar el nombre del método de la
             * superclase, y verá su utilidad. Si no escribimos la annotation,
             * funciona igual, pero ya no nos avisa si hay cambios en la
             * superclase. Por default, las clases extienden de Object.
             *
             */
            public void run() {
                new FrameAccesoPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblBackDoor;
    // End of variables declaration//GEN-END:variables
}
