/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author henrypb
 */
public class PanelReporteFactura extends javax.swing.JPanel {

    public JButton btnConforme; 
    public JButton btnCancelar;  
    
    /**
     * Creates new form PanelReporteFactura
     */
    public PanelReporteFactura() {
        initComponents();
        iniciar(); 
    }
    
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    private void iniciar() {
        // ** iniciar vars y atributos ** 
        String factura1 = PanelPostearFactura.txtNroFactura.getText(); 
        txtFactura1.setText(factura1);
        txtFactura2.setText(factura1);
        iniciarSppBotonera();  
    }
    
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    private void iniciarSppBotonera() {
        btnConforme = new JButton("Conforme");
        btnConforme.setFont(new Font("sansserif", Font.BOLD, 12));
        //ImageIcon iconConforme = new ImageIcon("../bean/utilitario/imagenes/checkMark16px.png"); // Revisar no funcionó. 
        ImageIcon iconConforme = new javax.swing.ImageIcon(getClass().getResource("/bean/utilitario/imagenes/checkMark16px.png")); 
        btnConforme.setIcon(iconConforme); 
        btnCancelar = new JButton("Cancelar");
        btnCancelar.setFont(new Font("sansserif", Font.BOLD, 12));
        ImageIcon iconCancelar = new javax.swing.ImageIcon(getClass().getResource("/bean/utilitario/imagenes/retornar16px.png")); 
        btnCancelar.setIcon(iconCancelar);
        sppBotonera.setLeftComponent(btnConforme);
        sppBotonera.setRightComponent(btnCancelar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sppBotonera = new javax.swing.JSplitPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFactura2 = new javax.swing.JTextField();
        txtFactura1 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(235, 120, 96));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel1.setText("       Parametros del Reporte");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 60));
        add(sppBotonera, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel2.setText("(1). Desde la factura :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel3.setText("(2). Hasta la factura : ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        txtFactura2.setText("012345");
        add(txtFactura2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 70, -1));

        txtFactura1.setText("0");
        add(txtFactura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 70, -1));
    }// </editor-fold>//GEN-END:initComponents
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JSplitPane sppBotonera;
    public static javax.swing.JTextField txtFactura1;
    public static javax.swing.JTextField txtFactura2;
    // End of variables declaration//GEN-END:variables

}
