package bean.entidad;
// Generated 12-ago-2014 15:06:22 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * CxcdDat generated by hbm2java
 */
public class CxcdDat  implements java.io.Serializable {


     private String codigo;
     private String codigoContable;
     private String nombreCliProv;
     private String nombreCliProv01;
     private String razonSocial;
     private String direccion1;
     private String direccion2;
     private String direccion3;
     private String telefono;
     private String cedula;
     private String fechaEmisionRif;
     private String fechaVencRif;
     private BigDecimal montoCompras;
     private BigDecimal limiteCredito;
     private String tipoDeCliente;
     private BigDecimal totalDebitos;
     private BigDecimal totalCreditos;
     private BigDecimal debitosPeriodo;
     private BigDecimal creditosPeriodo;
     private String tipoProveedor;
     private String personaContacto;
     private String tiempoEntrega;
     private String origen;
     private String ubicGeograf;
     private String pais;
     private String estado;
     private String ciudad;
     private String municipio;
     private String codPostal;
     private String contribuyente;
     private String nit;
     private String nroPatente;
     private String agenteRetencion;
     private Date fechaActExpediente;

    public CxcdDat() {
    }

	
    public CxcdDat(String codigo) {
        this.codigo = codigo;
    }
    public CxcdDat(String codigo, String codigoContable, String nombreCliProv, String nombreCliProv01, String razonSocial, String direccion1, String direccion2, String direccion3, String telefono, String cedula, String fechaEmisionRif, String fechaVencRif, BigDecimal montoCompras, BigDecimal limiteCredito, String tipoDeCliente, BigDecimal totalDebitos, BigDecimal totalCreditos, BigDecimal debitosPeriodo, BigDecimal creditosPeriodo, String tipoProveedor, String personaContacto, String tiempoEntrega, String origen, String ubicGeograf, String pais, String estado, String ciudad, String municipio, String codPostal, String contribuyente, String nit, String nroPatente, String agenteRetencion, Date fechaActExpediente) {
       this.codigo = codigo;
       this.codigoContable = codigoContable;
       this.nombreCliProv = nombreCliProv;
       this.nombreCliProv01 = nombreCliProv01;
       this.razonSocial = razonSocial;
       this.direccion1 = direccion1;
       this.direccion2 = direccion2;
       this.direccion3 = direccion3;
       this.telefono = telefono;
       this.cedula = cedula;
       this.fechaEmisionRif = fechaEmisionRif;
       this.fechaVencRif = fechaVencRif;
       this.montoCompras = montoCompras;
       this.limiteCredito = limiteCredito;
       this.tipoDeCliente = tipoDeCliente;
       this.totalDebitos = totalDebitos;
       this.totalCreditos = totalCreditos;
       this.debitosPeriodo = debitosPeriodo;
       this.creditosPeriodo = creditosPeriodo;
       this.tipoProveedor = tipoProveedor;
       this.personaContacto = personaContacto;
       this.tiempoEntrega = tiempoEntrega;
       this.origen = origen;
       this.ubicGeograf = ubicGeograf;
       this.pais = pais;
       this.estado = estado;
       this.ciudad = ciudad;
       this.municipio = municipio;
       this.codPostal = codPostal;
       this.contribuyente = contribuyente;
       this.nit = nit;
       this.nroPatente = nroPatente;
       this.agenteRetencion = agenteRetencion;
       this.fechaActExpediente = fechaActExpediente;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getCodigoContable() {
        return this.codigoContable;
    }
    
    public void setCodigoContable(String codigoContable) {
        this.codigoContable = codigoContable;
    }
    public String getNombreCliProv() {
        return this.nombreCliProv;
    }
    
    public void setNombreCliProv(String nombreCliProv) {
        this.nombreCliProv = nombreCliProv;
    }
    public String getNombreCliProv01() {
        return this.nombreCliProv01;
    }
    
    public void setNombreCliProv01(String nombreCliProv01) {
        this.nombreCliProv01 = nombreCliProv01;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getDireccion1() {
        return this.direccion1;
    }
    
    public void setDireccion1(String direccion1) {
        this.direccion1 = direccion1;
    }
    public String getDireccion2() {
        return this.direccion2;
    }
    
    public void setDireccion2(String direccion2) {
        this.direccion2 = direccion2;
    }
    public String getDireccion3() {
        return this.direccion3;
    }
    
    public void setDireccion3(String direccion3) {
        this.direccion3 = direccion3;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getFechaEmisionRif() {
        return this.fechaEmisionRif;
    }
    
    public void setFechaEmisionRif(String fechaEmisionRif) {
        this.fechaEmisionRif = fechaEmisionRif;
    }
    public String getFechaVencRif() {
        return this.fechaVencRif;
    }
    
    public void setFechaVencRif(String fechaVencRif) {
        this.fechaVencRif = fechaVencRif;
    }
    public BigDecimal getMontoCompras() {
        return this.montoCompras;
    }
    
    public void setMontoCompras(BigDecimal montoCompras) {
        this.montoCompras = montoCompras;
    }
    public BigDecimal getLimiteCredito() {
        return this.limiteCredito;
    }
    
    public void setLimiteCredito(BigDecimal limiteCredito) {
        this.limiteCredito = limiteCredito;
    }
    public String getTipoDeCliente() {
        return this.tipoDeCliente;
    }
    
    public void setTipoDeCliente(String tipoDeCliente) {
        this.tipoDeCliente = tipoDeCliente;
    }
    public BigDecimal getTotalDebitos() {
        return this.totalDebitos;
    }
    
    public void setTotalDebitos(BigDecimal totalDebitos) {
        this.totalDebitos = totalDebitos;
    }
    public BigDecimal getTotalCreditos() {
        return this.totalCreditos;
    }
    
    public void setTotalCreditos(BigDecimal totalCreditos) {
        this.totalCreditos = totalCreditos;
    }
    public BigDecimal getDebitosPeriodo() {
        return this.debitosPeriodo;
    }
    
    public void setDebitosPeriodo(BigDecimal debitosPeriodo) {
        this.debitosPeriodo = debitosPeriodo;
    }
    public BigDecimal getCreditosPeriodo() {
        return this.creditosPeriodo;
    }
    
    public void setCreditosPeriodo(BigDecimal creditosPeriodo) {
        this.creditosPeriodo = creditosPeriodo;
    }
    public String getTipoProveedor() {
        return this.tipoProveedor;
    }
    
    public void setTipoProveedor(String tipoProveedor) {
        this.tipoProveedor = tipoProveedor;
    }
    public String getPersonaContacto() {
        return this.personaContacto;
    }
    
    public void setPersonaContacto(String personaContacto) {
        this.personaContacto = personaContacto;
    }
    public String getTiempoEntrega() {
        return this.tiempoEntrega;
    }
    
    public void setTiempoEntrega(String tiempoEntrega) {
        this.tiempoEntrega = tiempoEntrega;
    }
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }
    public String getUbicGeograf() {
        return this.ubicGeograf;
    }
    
    public void setUbicGeograf(String ubicGeograf) {
        this.ubicGeograf = ubicGeograf;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public String getCodPostal() {
        return this.codPostal;
    }
    
    public void setCodPostal(String codPostal) {
        this.codPostal = codPostal;
    }
    public String getContribuyente() {
        return this.contribuyente;
    }
    
    public void setContribuyente(String contribuyente) {
        this.contribuyente = contribuyente;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getNroPatente() {
        return this.nroPatente;
    }
    
    public void setNroPatente(String nroPatente) {
        this.nroPatente = nroPatente;
    }
    public String getAgenteRetencion() {
        return this.agenteRetencion;
    }
    
    public void setAgenteRetencion(String agenteRetencion) {
        this.agenteRetencion = agenteRetencion;
    }
    public Date getFechaActExpediente() {
        return this.fechaActExpediente;
    }
    
    public void setFechaActExpediente(Date fechaActExpediente) {
        this.fechaActExpediente = fechaActExpediente;
    }




}


