package entidad;
// Generated 05-nov-2014 11:34:04 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Flete04DatId generated by hbm2java
 */
public class Flete04DatId  implements java.io.Serializable {


     private Date c4FechaRelacion;
     private String c4CodDestino;
     private String c4CodSector;

    public Flete04DatId() {
    }

    public Flete04DatId(Date c4FechaRelacion, String c4CodDestino, String c4CodSector) {
       this.c4FechaRelacion = c4FechaRelacion;
       this.c4CodDestino = c4CodDestino;
       this.c4CodSector = c4CodSector;
    }
   
    public Date getC4FechaRelacion() {
        return this.c4FechaRelacion;
    }
    
    public void setC4FechaRelacion(Date c4FechaRelacion) {
        this.c4FechaRelacion = c4FechaRelacion;
    }
    public String getC4CodDestino() {
        return this.c4CodDestino;
    }
    
    public void setC4CodDestino(String c4CodDestino) {
        this.c4CodDestino = c4CodDestino;
    }
    public String getC4CodSector() {
        return this.c4CodSector;
    }
    
    public void setC4CodSector(String c4CodSector) {
        this.c4CodSector = c4CodSector;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Flete04DatId) ) return false;
		 Flete04DatId castOther = ( Flete04DatId ) other; 
         
		 return ( (this.getC4FechaRelacion()==castOther.getC4FechaRelacion()) || ( this.getC4FechaRelacion()!=null && castOther.getC4FechaRelacion()!=null && this.getC4FechaRelacion().equals(castOther.getC4FechaRelacion()) ) )
 && ( (this.getC4CodDestino()==castOther.getC4CodDestino()) || ( this.getC4CodDestino()!=null && castOther.getC4CodDestino()!=null && this.getC4CodDestino().equals(castOther.getC4CodDestino()) ) )
 && ( (this.getC4CodSector()==castOther.getC4CodSector()) || ( this.getC4CodSector()!=null && castOther.getC4CodSector()!=null && this.getC4CodSector().equals(castOther.getC4CodSector()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getC4FechaRelacion() == null ? 0 : this.getC4FechaRelacion().hashCode() );
         result = 37 * result + ( getC4CodDestino() == null ? 0 : this.getC4CodDestino().hashCode() );
         result = 37 * result + ( getC4CodSector() == null ? 0 : this.getC4CodSector().hashCode() );
         return result;
   }   


}


