package entidad;
// Generated 05-nov-2014 11:34:04 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Flete04Dat generated by hbm2java
 */
public class Flete04Dat  implements java.io.Serializable {


     private Flete04DatId id;
     private Flete03Dat flete03Dat;
     private String c4CodPais;
     private String c4CodEstado;
     private String c4NombreDestino;
     private String c4CodPostal;
     private BigDecimal c4PrecioTonCamion;
     private BigDecimal c4PrecioTonGandola;
     private BigDecimal c4PrecioTonToronto;
     private BigDecimal c4PrecioTonEspecial;
     private String c4CodMonExtCamion;
     private BigDecimal c4PrecioTonCamionMe;
     private String c4CodMonExtGandola;
     private BigDecimal c4PrecioTonGandolaMe;
     private String c4CodMonExtToronto;
     private BigDecimal c4PrecioTonTorontoMe;
     private String c4CodMonExtPrecioEsp;
     private BigDecimal c4PrecioTonEspecialMe;

    public Flete04Dat() {
    }

	
    public Flete04Dat(Flete04DatId id, Flete03Dat flete03Dat, String c4CodEstado, String c4NombreDestino) {
        this.id = id;
        this.flete03Dat = flete03Dat;
        this.c4CodEstado = c4CodEstado;
        this.c4NombreDestino = c4NombreDestino;
    }

    public Flete04Dat(Flete04DatId id, Flete03Dat flete03Dat, String c4CodPais, String c4CodEstado, String c4NombreDestino, String c4CodPostal, BigDecimal c4PrecioTonCamion, BigDecimal c4PrecioTonGandola, BigDecimal c4PrecioTonToronto, BigDecimal c4PrecioTonEspecial, String c4CodMonExtCamion, BigDecimal c4PrecioTonCamionMe, String c4CodMonExtGandola, BigDecimal c4PrecioTonGandolaMe, String c4CodMonExtToronto, BigDecimal c4PrecioTonTorontoMe, String c4CodMonExtPrecioEsp, BigDecimal c4PrecioTonEspecialMe) {
        this.id = id;
        this.flete03Dat = flete03Dat;
        this.c4CodPais = c4CodPais;
        this.c4CodEstado = c4CodEstado;
        this.c4NombreDestino = c4NombreDestino;
        this.c4CodPostal = c4CodPostal;
        this.c4PrecioTonCamion = c4PrecioTonCamion;
        this.c4PrecioTonGandola = c4PrecioTonGandola;
        this.c4PrecioTonToronto = c4PrecioTonToronto;
        this.c4PrecioTonEspecial = c4PrecioTonEspecial;
        this.c4CodMonExtCamion = c4CodMonExtCamion;
        this.c4PrecioTonCamionMe = c4PrecioTonCamionMe;
        this.c4CodMonExtGandola = c4CodMonExtGandola;
        this.c4PrecioTonGandolaMe = c4PrecioTonGandolaMe;
        this.c4CodMonExtToronto = c4CodMonExtToronto;
        this.c4PrecioTonTorontoMe = c4PrecioTonTorontoMe;
        this.c4CodMonExtPrecioEsp = c4CodMonExtPrecioEsp;
        this.c4PrecioTonEspecialMe = c4PrecioTonEspecialMe;
    }

    public Flete04DatId getId() {
        return this.id;
    }
    
    public void setId(Flete04DatId id) {
        this.id = id;
    }
    public Flete03Dat getFlete03Dat() {
        return this.flete03Dat;
    }
    
    public void setFlete03Dat(Flete03Dat flete03Dat) {
        this.flete03Dat = flete03Dat;
    }
    public String getC4CodPais() {
        return this.c4CodPais;
    }
    
    public void setC4CodPais(String c4CodPais) {
        this.c4CodPais = c4CodPais;
    }
    public String getC4CodEstado() {
        return this.c4CodEstado;
    }
    
    public void setC4CodEstado(String c4CodEstado) {
        this.c4CodEstado = c4CodEstado;
    }
    public String getC4NombreDestino() {
        return this.c4NombreDestino;
    }
    
    public void setC4NombreDestino(String c4NombreDestino) {
        this.c4NombreDestino = c4NombreDestino;
    }
    public String getC4CodPostal() {
        return this.c4CodPostal;
    }
    
    public void setC4CodPostal(String c4CodPostal) {
        this.c4CodPostal = c4CodPostal;
    }
    public BigDecimal getC4PrecioTonCamion() {
        return this.c4PrecioTonCamion;
    }
    
    public void setC4PrecioTonCamion(BigDecimal c4PrecioTonCamion) {
        this.c4PrecioTonCamion = c4PrecioTonCamion;
    }
    public BigDecimal getC4PrecioTonGandola() {
        return this.c4PrecioTonGandola;
    }
    
    public void setC4PrecioTonGandola(BigDecimal c4PrecioTonGandola) {
        this.c4PrecioTonGandola = c4PrecioTonGandola;
    }
    public BigDecimal getC4PrecioTonToronto() {
        return this.c4PrecioTonToronto;
    }
    
    public void setC4PrecioTonToronto(BigDecimal c4PrecioTonToronto) {
        this.c4PrecioTonToronto = c4PrecioTonToronto;
    }

    public String getC4CodMonExtPrecioEsp() {
        return c4CodMonExtPrecioEsp;
    }

    public void setC4CodMonExtPrecioEsp(String c4CodMonExtPrecioEsp) {
        this.c4CodMonExtPrecioEsp = c4CodMonExtPrecioEsp;
    }
    
    public BigDecimal getC4PrecioTonEspecial() {
        return this.c4PrecioTonEspecial;
    }
    
    public void setC4PrecioTonEspecial(BigDecimal c4PrecioEspecial) {
        this.c4PrecioTonEspecial = c4PrecioEspecial;
    }
    public String getC4CodMonExtCamion() {
        return this.c4CodMonExtCamion;
    }
    
    public void setC4CodMonExtCamion(String c4CodMonExtCamion) {
        this.c4CodMonExtCamion = c4CodMonExtCamion;
    }
    public BigDecimal getC4PrecioTonCamionMe() {
        return this.c4PrecioTonCamionMe;
    }
    
    public void setC4PrecioTonCamionMe(BigDecimal c4PrecioTonCamionMe) {
        this.c4PrecioTonCamionMe = c4PrecioTonCamionMe;
    }
    public String getC4CodMonExtGandola() {
        return this.c4CodMonExtGandola;
    }
    
    public void setC4CodMonExtGandola(String c4CodMonExtGandola) {
        this.c4CodMonExtGandola = c4CodMonExtGandola;
    }
    public BigDecimal getC4PrecioTonGandolaMe() {
        return this.c4PrecioTonGandolaMe;
    }
    
    public void setC4PrecioTonGandolaMe(BigDecimal c4PrecioTonGandolaMe) {
        this.c4PrecioTonGandolaMe = c4PrecioTonGandolaMe;
    }
    public String getC4CodMonExtToronto() {
        return this.c4CodMonExtToronto;
    }
    
    public void setC4CodMonExtToronto(String c4CodMonExtToronto) {
        this.c4CodMonExtToronto = c4CodMonExtToronto;
    }
    public BigDecimal getC4PrecioTonTorontoMe() {
        return this.c4PrecioTonTorontoMe;
    }
    
    public void setC4PrecioTonTorontoMe(BigDecimal c4PrecioTonTorontoMe) {
        this.c4PrecioTonTorontoMe = c4PrecioTonTorontoMe;
    }
    public BigDecimal getC4PrecioTonEspecialMe() {
        return this.c4PrecioTonEspecialMe;
    }
    
    public void setC4PrecioTonEspecialMe(BigDecimal c4PrecioEspecialMe) {
        this.c4PrecioTonEspecialMe = c4PrecioEspecialMe;
    }

}


