package entidad;
// Generated 06-oct-2014 12:18:56 by Hibernate Tools 4.3.1



/**
 * Guias02DatId generated by hbm2java
 */
public class Guias02DatId  implements java.io.Serializable {


     private String c2Guia;
     private byte c2ItemNo;
     private String c2Codigo;

    public Guias02DatId() {
    }

    public Guias02DatId(String c2Guia, byte c2ItemNo, String c2Codigo) {
       this.c2Guia = c2Guia;
       this.c2ItemNo = c2ItemNo;
       this.c2Codigo = c2Codigo;
    }
   
    public String getC2Guia() {
        return this.c2Guia;
    }
    
    public void setC2Guia(String c2Guia) {
        this.c2Guia = c2Guia;
    }
    public byte getC2ItemNo() {
        return this.c2ItemNo;
    }
    
    public void setC2ItemNo(byte c2ItemNo) {
        this.c2ItemNo = c2ItemNo;
    }
    public String getC2Codigo() {
        return this.c2Codigo;
    }
    
    public void setC2Codigo(String c2Codigo) {
        this.c2Codigo = c2Codigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Guias02DatId) ) return false;
		 Guias02DatId castOther = ( Guias02DatId ) other; 
         
		 return ( (this.getC2Guia()==castOther.getC2Guia()) || ( this.getC2Guia()!=null && castOther.getC2Guia()!=null && this.getC2Guia().equals(castOther.getC2Guia()) ) )
 && (this.getC2ItemNo()==castOther.getC2ItemNo())
 && ( (this.getC2Codigo()==castOther.getC2Codigo()) || ( this.getC2Codigo()!=null && castOther.getC2Codigo()!=null && this.getC2Codigo().equals(castOther.getC2Codigo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getC2Guia() == null ? 0 : this.getC2Guia().hashCode() );
         result = 37 * result + this.getC2ItemNo();
         result = 37 * result + ( getC2Codigo() == null ? 0 : this.getC2Codigo().hashCode() );
         return result;
   }   


}


