package entidad;
// Generated 06-oct-2014 12:18:56 by Hibernate Tools 4.3.1


import bean.entidad.Guias01Dat;
import java.math.BigDecimal;

/**
 * Guias02Dat generated by hbm2java
 */
public class Guias02Dat  implements java.io.Serializable {


     private Guias02DatId id;
     private Guias01Dat guias01Dat;
     private String c2Tipo;
     private String c2Descripcion;
     private BigDecimal c2Peso;
     private String c2NoPedido;
     private Integer c2Unidades;
     private Short c2Items;
     private String c2Atados;
     private BigDecimal c2Precio;
     private BigDecimal c2Alicuota;
     private String c2Fxpeso;
     private String c2Fxunidad;
     private BigDecimal c2PesoGuia;

    public Guias02Dat() {
    }

	
    public Guias02Dat(Guias02DatId id, Guias01Dat guias01Dat) {
        this.id = id;
        this.guias01Dat = guias01Dat;
    }
    public Guias02Dat(Guias02DatId id, Guias01Dat guias01Dat, String c2Tipo, String c2Descripcion, BigDecimal c2Peso, String c2NoPedido, Integer c2Unidades, Short c2Items, String c2Atados, BigDecimal c2Precio, BigDecimal c2Alicuota, String c2Fxpeso, String c2Fxunidad, BigDecimal c2PesoGuia) {
       this.id = id;
       this.guias01Dat = guias01Dat;
       this.c2Tipo = c2Tipo;
       this.c2Descripcion = c2Descripcion;
       this.c2Peso = c2Peso;
       this.c2NoPedido = c2NoPedido;
       this.c2Unidades = c2Unidades;
       this.c2Items = c2Items;
       this.c2Atados = c2Atados;
       this.c2Precio = c2Precio;
       this.c2Alicuota = c2Alicuota;
       this.c2Fxpeso = c2Fxpeso;
       this.c2Fxunidad = c2Fxunidad;
       this.c2PesoGuia = c2PesoGuia;
    }
   
    public Guias02DatId getId() {
        return this.id;
    }
    
    public void setId(Guias02DatId id) {
        this.id = id;
    }
    public Guias01Dat getGuias01Dat() {
        return this.guias01Dat;
    }
    
    public void setGuias01Dat(Guias01Dat guias01Dat) {
        this.guias01Dat = guias01Dat;
    }
    public String getC2Tipo() {
        return this.c2Tipo;
    }
    
    public void setC2Tipo(String c2Tipo) {
        this.c2Tipo = c2Tipo;
    }
    public String getC2Descripcion() {
        return this.c2Descripcion;
    }
    
    public void setC2Descripcion(String c2Descripcion) {
        this.c2Descripcion = c2Descripcion;
    }
    public BigDecimal getC2Peso() {
        return this.c2Peso;
    }
    
    public void setC2Peso(BigDecimal c2Peso) {
        this.c2Peso = c2Peso;
    }
    public String getC2NoPedido() {
        return this.c2NoPedido;
    }
    
    public void setC2NoPedido(String c2NoPedido) {
        this.c2NoPedido = c2NoPedido;
    }
    public Integer getC2Unidades() {
        return this.c2Unidades;
    }
    
    public void setC2Unidades(Integer c2Unidades) {
        this.c2Unidades = c2Unidades;
    }
    public Short getC2Items() {
        return this.c2Items;
    }
    
    public void setC2Items(Short c2Items) {
        this.c2Items = c2Items;
    }
    public String getC2Atados() {
        return this.c2Atados;
    }
    
    public void setC2Atados(String c2Atados) {
        this.c2Atados = c2Atados;
    }
    public BigDecimal getC2Precio() {
        return this.c2Precio;
    }
    
    public void setC2Precio(BigDecimal c2Precio) {
        this.c2Precio = c2Precio;
    }
    public BigDecimal getC2Alicuota() {
        return this.c2Alicuota;
    }
    
    public void setC2Alicuota(BigDecimal c2Alicuota) {
        this.c2Alicuota = c2Alicuota;
    }
    public String getC2Fxpeso() {
        return this.c2Fxpeso;
    }
    
    public void setC2Fxpeso(String c2Fxpeso) {
        this.c2Fxpeso = c2Fxpeso;
    }
    public String getC2Fxunidad() {
        return this.c2Fxunidad;
    }
    
    public void setC2Fxunidad(String c2Fxunidad) {
        this.c2Fxunidad = c2Fxunidad;
    }
    public BigDecimal getC2PesoGuia() {
        return this.c2PesoGuia;
    }
    
    public void setC2PesoGuia(BigDecimal c2PesoGuia) {
        this.c2PesoGuia = c2PesoGuia;
    }




}


