package bean.entidad;
// Generated 05-sep-2014 14:23:58 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Inv04Dat generated by hbm2java
 */
public class Inv04Dat  implements java.io.Serializable {


     private Inv04DatId id;
     private Inv03Dat inv03Dat;
     private String c4TipoProd;
     private BigDecimal c4Taml;
     private BigDecimal c4Tamt;
     private BigDecimal c4Sepl;
     private BigDecimal c4Sept;
     private BigDecimal c4Diaml;
     private BigDecimal c4Diamt;
     private Short c4Numl;
     private Short c4Numt;
     private Short c4Sobrl1;
     private Short c4Sobrl2;
     private Short c4Sobrt1;
     private Short c4Sobrt2;
     private BigDecimal c4PesoItem;
     private Integer c4Lam;
     private BigDecimal c4Bsxton;
     private String c4CodContable;

    public Inv04Dat() {
    }

	
    public Inv04Dat(Inv04DatId id, Inv03Dat inv03Dat) {
        this.id = id;
        this.inv03Dat = inv03Dat;
    }
    public Inv04Dat(Inv04DatId id, Inv03Dat inv03Dat, String c4TipoProd, BigDecimal c4Taml, BigDecimal c4Tamt, BigDecimal c4Sepl, BigDecimal c4Sept, BigDecimal c4Diaml, BigDecimal c4Diamt, Short c4Numl, Short c4Numt, Short c4Sobrl1, Short c4Sobrl2, Short c4Sobrt1, Short c4Sobrt2, BigDecimal c4PesoItem, Integer c4Lam, BigDecimal c4Bsxton, String c4CodContable) {
       this.id = id;
       this.inv03Dat = inv03Dat;
       this.c4TipoProd = c4TipoProd;
       this.c4Taml = c4Taml;
       this.c4Tamt = c4Tamt;
       this.c4Sepl = c4Sepl;
       this.c4Sept = c4Sept;
       this.c4Diaml = c4Diaml;
       this.c4Diamt = c4Diamt;
       this.c4Numl = c4Numl;
       this.c4Numt = c4Numt;
       this.c4Sobrl1 = c4Sobrl1;
       this.c4Sobrl2 = c4Sobrl2;
       this.c4Sobrt1 = c4Sobrt1;
       this.c4Sobrt2 = c4Sobrt2;
       this.c4PesoItem = c4PesoItem;
       this.c4Lam = c4Lam;
       this.c4Bsxton = c4Bsxton;
       this.c4CodContable = c4CodContable;
    }
   
    public Inv04DatId getId() {
        return this.id;
    }
    
    public void setId(Inv04DatId id) {
        this.id = id;
    }
    public Inv03Dat getInv03Dat() {
        return this.inv03Dat;
    }
    
    public void setInv03Dat(Inv03Dat inv03Dat) {
        this.inv03Dat = inv03Dat;
    }
    public String getC4TipoProd() {
        return this.c4TipoProd;
    }
    
    public void setC4TipoProd(String c4TipoProd) {
        this.c4TipoProd = c4TipoProd;
    }
    public BigDecimal getC4Taml() {
        return this.c4Taml;
    }
    
    public void setC4Taml(BigDecimal c4Taml) {
        this.c4Taml = c4Taml;
    }
    public BigDecimal getC4Tamt() {
        return this.c4Tamt;
    }
    
    public void setC4Tamt(BigDecimal c4Tamt) {
        this.c4Tamt = c4Tamt;
    }
    public BigDecimal getC4Sepl() {
        return this.c4Sepl;
    }
    
    public void setC4Sepl(BigDecimal c4Sepl) {
        this.c4Sepl = c4Sepl;
    }
    public BigDecimal getC4Sept() {
        return this.c4Sept;
    }
    
    public void setC4Sept(BigDecimal c4Sept) {
        this.c4Sept = c4Sept;
    }
    public BigDecimal getC4Diaml() {
        return this.c4Diaml;
    }
    
    public void setC4Diaml(BigDecimal c4Diaml) {
        this.c4Diaml = c4Diaml;
    }
    public BigDecimal getC4Diamt() {
        return this.c4Diamt;
    }
    
    public void setC4Diamt(BigDecimal c4Diamt) {
        this.c4Diamt = c4Diamt;
    }
    public Short getC4Numl() {
        return this.c4Numl;
    }
    
    public void setC4Numl(Short c4Numl) {
        this.c4Numl = c4Numl;
    }
    public Short getC4Numt() {
        return this.c4Numt;
    }
    
    public void setC4Numt(Short c4Numt) {
        this.c4Numt = c4Numt;
    }
    public Short getC4Sobrl1() {
        return this.c4Sobrl1;
    }
    
    public void setC4Sobrl1(Short c4Sobrl1) {
        this.c4Sobrl1 = c4Sobrl1;
    }
    public Short getC4Sobrl2() {
        return this.c4Sobrl2;
    }
    
    public void setC4Sobrl2(Short c4Sobrl2) {
        this.c4Sobrl2 = c4Sobrl2;
    }
    public Short getC4Sobrt1() {
        return this.c4Sobrt1;
    }
    
    public void setC4Sobrt1(Short c4Sobrt1) {
        this.c4Sobrt1 = c4Sobrt1;
    }
    public Short getC4Sobrt2() {
        return this.c4Sobrt2;
    }
    
    public void setC4Sobrt2(Short c4Sobrt2) {
        this.c4Sobrt2 = c4Sobrt2;
    }
    public BigDecimal getC4PesoItem() {
        return this.c4PesoItem;
    }
    
    public void setC4PesoItem(BigDecimal c4PesoItem) {
        this.c4PesoItem = c4PesoItem;
    }
    public Integer getC4Lam() {
        return this.c4Lam;
    }
    
    public void setC4Lam(Integer c4Lam) {
        this.c4Lam = c4Lam;
    }
    public BigDecimal getC4Bsxton() {
        return this.c4Bsxton;
    }
    
    public void setC4Bsxton(BigDecimal c4Bsxton) {
        this.c4Bsxton = c4Bsxton;
    }
    public String getC4CodContable() {
        return this.c4CodContable;
    }
    
    public void setC4CodContable(String c4CodContable) {
        this.c4CodContable = c4CodContable;
    }




}


