package bean.entidad;
// Generated 28-ago-2014 14:55:07 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Inv08Dat generated by hbm2java
 */
public class Inv08Dat  implements java.io.Serializable {


     private Inv08DatId id;
     private Inv07Dat inv07Dat;
     private String c8Tipo;
     private String c8Descripcion;
     private String c8Guia;
     private BigDecimal c8Peso;
     private Integer c8Unidades;
     private BigDecimal c8Precio;
     private BigDecimal c8Flete;
     private String c8Fxunidad;
     private String c8Fxpeso;
     private BigDecimal c8PesoGuia;
     private BigDecimal c8Ajuste;

    public Inv08Dat() {
    }

	
    public Inv08Dat(Inv08DatId id, Inv07Dat inv07Dat) {
        this.id = id;
        this.inv07Dat = inv07Dat;
    }
    public Inv08Dat(Inv08DatId id, Inv07Dat inv07Dat, String c8Tipo, String c8Descripcion, String c8Guia, BigDecimal c8Peso, Integer c8Unidades, BigDecimal c8Precio, BigDecimal c8Flete, String c8Fxunidad, String c8Fxpeso, BigDecimal c8PesoGuia, BigDecimal c8Ajuste) {
       this.id = id;
       this.inv07Dat = inv07Dat;
       this.c8Tipo = c8Tipo;
       this.c8Descripcion = c8Descripcion;
       this.c8Guia = c8Guia;
       this.c8Peso = c8Peso;
       this.c8Unidades = c8Unidades;
       this.c8Precio = c8Precio;
       this.c8Flete = c8Flete;
       this.c8Fxunidad = c8Fxunidad;
       this.c8Fxpeso = c8Fxpeso;
       this.c8PesoGuia = c8PesoGuia;
       this.c8Ajuste = c8Ajuste;
    }
   
    public Inv08DatId getId() {
        return this.id;
    }
    
    public void setId(Inv08DatId id) {
        this.id = id;
    }
    public Inv07Dat getInv07Dat() {
        return this.inv07Dat;
    }
    
    public void setInv07Dat(Inv07Dat inv07Dat) {
        this.inv07Dat = inv07Dat;
    }
    public String getC8Tipo() {
        return this.c8Tipo;
    }
    
    public void setC8Tipo(String c8Tipo) {
        this.c8Tipo = c8Tipo;
    }
    public String getC8Descripcion() {
        return this.c8Descripcion;
    }
    
    public void setC8Descripcion(String c8Descripcion) {
        this.c8Descripcion = c8Descripcion;
    }
    public String getC8Guia() {
        return this.c8Guia;
    }
    
    public void setC8Guia(String c8Guia) {
        this.c8Guia = c8Guia;
    }
    public BigDecimal getC8Peso() {
        return this.c8Peso;
    }
    
    public void setC8Peso(BigDecimal c8Peso) {
        this.c8Peso = c8Peso;
    }
    public Integer getC8Unidades() {
        return this.c8Unidades;
    }
    
    public void setC8Unidades(Integer c8Unidades) {
        this.c8Unidades = c8Unidades;
    }
    public BigDecimal getC8Precio() {
        return this.c8Precio;
    }
    
    public void setC8Precio(BigDecimal c8Precio) {
        this.c8Precio = c8Precio;
    }
    public BigDecimal getC8Flete() {
        return this.c8Flete;
    }
    
    public void setC8Flete(BigDecimal c8Flete) {
        this.c8Flete = c8Flete;
    }
    public String getC8Fxunidad() {
        return this.c8Fxunidad;
    }
    
    public void setC8Fxunidad(String c8Fxunidad) {
        this.c8Fxunidad = c8Fxunidad;
    }
    public String getC8Fxpeso() {
        return this.c8Fxpeso;
    }
    
    public void setC8Fxpeso(String c8Fxpeso) {
        this.c8Fxpeso = c8Fxpeso;
    }
    public BigDecimal getC8PesoGuia() {
        return this.c8PesoGuia;
    }
    
    public void setC8PesoGuia(BigDecimal c8PesoGuia) {
        this.c8PesoGuia = c8PesoGuia;
    }
    public BigDecimal getC8Ajuste() {
        return this.c8Ajuste;
    }
    
    public void setC8Ajuste(BigDecimal c8Ajuste) {
        this.c8Ajuste = c8Ajuste;
    }

}


