package bean.entidad;
// Generated 28-ago-2014 14:55:07 by Hibernate Tools 3.6.0



/**
 * Inv08DatId generated by hbm2java
 */
public class Inv08DatId  implements java.io.Serializable {


     private String c8Factura;
     private String c8Codigo;
     private byte c8ItemNo;

    public Inv08DatId() {
    }

    public Inv08DatId(String c8Factura, String c8Codigo, byte c8ItemNo) {
       this.c8Factura = c8Factura;
       this.c8Codigo = c8Codigo;
       this.c8ItemNo = c8ItemNo;
    }
   
    public String getC8Factura() {
        return this.c8Factura;
    }
    
    public void setC8Factura(String c8Factura) {
        this.c8Factura = c8Factura;
    }
    public String getC8Codigo() {
        return this.c8Codigo;
    }
    
    public void setC8Codigo(String c8Codigo) {
        this.c8Codigo = c8Codigo;
    }
    public byte getC8ItemNo() {
        return this.c8ItemNo;
    }
    
    public void setC8ItemNo(byte c8ItemNo) {
        this.c8ItemNo = c8ItemNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Inv08DatId) ) return false;
		 Inv08DatId castOther = ( Inv08DatId ) other; 
         
		 return ( (this.getC8Factura()==castOther.getC8Factura()) || ( this.getC8Factura()!=null && castOther.getC8Factura()!=null && this.getC8Factura().equals(castOther.getC8Factura()) ) )
 && ( (this.getC8Codigo()==castOther.getC8Codigo()) || ( this.getC8Codigo()!=null && castOther.getC8Codigo()!=null && this.getC8Codigo().equals(castOther.getC8Codigo()) ) )
 && (this.getC8ItemNo()==castOther.getC8ItemNo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getC8Factura() == null ? 0 : this.getC8Factura().hashCode() );
         result = 37 * result + ( getC8Codigo() == null ? 0 : this.getC8Codigo().hashCode() );
         result = 37 * result + this.getC8ItemNo();
         return result;
   }   


}


