package bean.entidad;
// Generated 12-ago-2014 14:27:32 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Inv01Dat generated by hbm2java
 */
public class Inv01Dat  implements java.io.Serializable {


     private String c1Codigo;
     private String c1Tipo;
     private String c1Descripcion;
     private BigDecimal c1Espesor;
     private BigDecimal c1Longitud;
     private BigDecimal c1Ancho;
     private Integer c1Area;
     private String c1Separacion;
     private Integer c1ItemsAtado;
     private BigDecimal c1Peso;
     private BigDecimal c1PrecioActual;
     private String c1UnidadMedida;
     private String c1CodMaquina;
     private String c1Observacion;
     private Short c1Unidades;
     private String c1CodContable;

    public Inv01Dat() {
    }

	
    public Inv01Dat(String c1Codigo) {
        this.c1Codigo = c1Codigo;
    }
    public Inv01Dat(String c1Codigo, String c1Tipo, String c1Descripcion, BigDecimal c1Espesor, BigDecimal c1Longitud, BigDecimal c1Ancho, Integer c1Area, String c1Separacion, Integer c1ItemsAtado, BigDecimal c1Peso, BigDecimal c1PrecioActual, String c1UnidadMedida, String c1CodMaquina, String c1Observacion, Short c1Unidades, String c1CodContable) {
       this.c1Codigo = c1Codigo;
       this.c1Tipo = c1Tipo;
       this.c1Descripcion = c1Descripcion;
       this.c1Espesor = c1Espesor;
       this.c1Longitud = c1Longitud;
       this.c1Ancho = c1Ancho;
       this.c1Area = c1Area;
       this.c1Separacion = c1Separacion;
       this.c1ItemsAtado = c1ItemsAtado;
       this.c1Peso = c1Peso;
       this.c1PrecioActual = c1PrecioActual;
       this.c1UnidadMedida = c1UnidadMedida;
       this.c1CodMaquina = c1CodMaquina;
       this.c1Observacion = c1Observacion;
       this.c1Unidades = c1Unidades;
       this.c1CodContable = c1CodContable;
    }
   
    public String getC1Codigo() {
        return this.c1Codigo;
    }
    
    public void setC1Codigo(String c1Codigo) {
        this.c1Codigo = c1Codigo;
    }
    public String getC1Tipo() {
        return this.c1Tipo;
    }
    
    public void setC1Tipo(String c1Tipo) {
        this.c1Tipo = c1Tipo;
    }
    public String getC1Descripcion() {
        return this.c1Descripcion;
    }
    
    public void setC1Descripcion(String c1Descripcion) {
        this.c1Descripcion = c1Descripcion;
    }
    public BigDecimal getC1Espesor() {
        return this.c1Espesor;
    }
    
    public void setC1Espesor(BigDecimal c1Espesor) {
        this.c1Espesor = c1Espesor;
    }
    public BigDecimal getC1Longitud() {
        return this.c1Longitud;
    }
    
    public void setC1Longitud(BigDecimal c1Longitud) {
        this.c1Longitud = c1Longitud;
    }
    public BigDecimal getC1Ancho() {
        return this.c1Ancho;
    }
    
    public void setC1Ancho(BigDecimal c1Ancho) {
        this.c1Ancho = c1Ancho;
    }
    public Integer getC1Area() {
        return this.c1Area;
    }
    
    public void setC1Area(Integer c1Area) {
        this.c1Area = c1Area;
    }
    public String getC1Separacion() {
        return this.c1Separacion;
    }
    
    public void setC1Separacion(String c1Separacion) {
        this.c1Separacion = c1Separacion;
    }
    public Integer getC1ItemsAtado() {
        return this.c1ItemsAtado;
    }
    
    public void setC1ItemsAtado(Integer c1ItemsAtado) {
        this.c1ItemsAtado = c1ItemsAtado;
    }
    public BigDecimal getC1Peso() {
        return this.c1Peso;
    }
    
    public void setC1Peso(BigDecimal c1Peso) {
        this.c1Peso = c1Peso;
    }
    public BigDecimal getC1PrecioActual() {
        return this.c1PrecioActual;
    }
    
    public void setC1PrecioActual(BigDecimal c1PrecioActual) {
        this.c1PrecioActual = c1PrecioActual;
    }
    public String getC1UnidadMedida() {
        return this.c1UnidadMedida;
    }
    
    public void setC1UnidadMedida(String c1UnidadMedida) {
        this.c1UnidadMedida = c1UnidadMedida;
    }
    public String getC1CodMaquina() {
        return this.c1CodMaquina;
    }
    
    public void setC1CodMaquina(String c1CodMaquina) {
        this.c1CodMaquina = c1CodMaquina;
    }
    public String getC1Observacion() {
        return this.c1Observacion;
    }
    
    public void setC1Observacion(String c1Observacion) {
        this.c1Observacion = c1Observacion;
    }
    public Short getC1Unidades() {
        return this.c1Unidades;
    }
    
    public void setC1Unidades(Short c1Unidades) {
        this.c1Unidades = c1Unidades;
    }
    public String getC1CodContable() {
        return this.c1CodContable;
    }
    
    public void setC1CodContable(String c1CodContable) {
        this.c1CodContable = c1CodContable;
    }




}


