package bean.entidad;
// Generated 12-ago-2014 14:27:32 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Inv07Dat generated by hbm2java
 */
public class Inv07Dat  implements java.io.Serializable {


     private String c7Factura;
     private Date c7Fecha;
     private String c7ClienteEspecial;
     private String c7CodigoCliente;
     private String c7RazonSocial;
     private String c7Rif;
     private String c7Nit;
     private String c7Ncf;
     private String c7RetiradoPlanta;
     private String c7DirFiscal1;
     private String c7DirFiscal2;
     private String c7DirFiscal3;
     private String c7Entrega1;
     private String c7Entrega2;
     private String c7Entrega3;
     private String c7Entrega4;
     private String c7Orden1;
     private String c7Orden2;
     private String c7Financiar;
     private String c7CondicionesPago;
     private String c7Vendedor;
     private String c7Nombre;
     private String c7Zona;
     private String c7OrdenCompra1;
     private String c7OrdenCompra2;
     private String c7Pedido1;
     private String c7Pedido2;
     private BigDecimal c7DescPerCent;
     private BigDecimal c7PerCentFlete;
     private Short c7Plazo;
     private String c7Guia1;
     private String c7Guia2;
     private Date c7FechaGuia;
     private BigDecimal c7MontoFlete;
     private BigDecimal c7MontoAjuste; 
     private BigDecimal c7ReconociFlete;
     private BigDecimal c7Descuento;
     private BigDecimal c7Ivm;
     private BigDecimal c7Anticipo;
     private BigDecimal c7IvmAnt;
     private BigDecimal c7CambioMoneda;
     private String  c7Nc; 
     private String c7Status;
     private Set inv08Dats = new HashSet(0);
     
    // CAMPOS CALCULADOS:>> No son de la Base de Datos: 
    private BigDecimal montoFactura; 
    private BigDecimal sumPesoGuia;  
    private BigDecimal sumFlete;  
    private BigDecimal sumAjuste; 
    private BigDecimal subTotal;  
    private BigDecimal depGarantia; 
    private BigDecimal totalFactura;  
     
     
    public Inv07Dat() {
    }

	
    public Inv07Dat(String c7Factura) {
        this.c7Factura = c7Factura;
    }

    /*
    public Inv07DatOLD(String c7Factura, Date c7Fecha, String c7ClienteEspecial, String c7CodigoCliente, String c7RazonSocial, String c7Rif, String c7Nit, String c7Ncf, String c7RetiradoPlanta, String c7DirFiscal1, String c7DirFiscal2, String c7DirFiscal3, String c7Entrega1, String c7Entrega2, String c7Entrega3, String c7Entrega4, String c7Orden1, String c7Orden2, String c7Financiar, String c7CondicionesPago, String c7Vendedor, String c7Nombre, String c7Zona, String c7OrdenCompra1, String c7OrdenCompra2, String c7Pedido1, String c7Pedido2, BigDecimal c7DescPerCent, BigDecimal c7PerCentFlete, Short c7Plazo, String c7Guia1, String c7Guia2, Date c7FechaGuia, BigDecimal c7MontoFlete, BigDecimal c7ReconociFlete, BigDecimal c7Descuento, BigDecimal c7MontoAjuste, BigDecimal c7Ivm, BigDecimal c7Anticipo, BigDecimal c7IvmAnt, BigDecimal c7CambioMoneda, String c7Nc, String c7Status, Set inv08Dats) {
       this.c7Factura = c7Factura;
       this.c7Fecha = c7Fecha;
       this.c7ClienteEspecial = c7ClienteEspecial;
       this.c7CodigoCliente = c7CodigoCliente;
       this.c7RazonSocial = c7RazonSocial;
       this.c7Rif = c7Rif;
       this.c7Nit = c7Nit;
       this.c7Ncf = c7Ncf;
       this.c7RetiradoPlanta = c7RetiradoPlanta;
       this.c7DirFiscal1 = c7DirFiscal1;
       this.c7DirFiscal2 = c7DirFiscal2;
       this.c7DirFiscal3 = c7DirFiscal3;
       this.c7Entrega1 = c7Entrega1;
       this.c7Entrega2 = c7Entrega2;
       this.c7Entrega3 = c7Entrega3;
       this.c7Entrega4 = c7Entrega4;
       this.c7Orden1 = c7Orden1;
       this.c7Orden2 = c7Orden2;
       this.c7Financiar = c7Financiar;
       this.c7CondicionesPago = c7CondicionesPago;
       this.c7Vendedor = c7Vendedor;
       this.c7Nombre = c7Nombre;
       this.c7Zona = c7Zona;
       this.c7OrdenCompra1 = c7OrdenCompra1;
       this.c7OrdenCompra2 = c7OrdenCompra2;
       this.c7Pedido1 = c7Pedido1;
       this.c7Pedido2 = c7Pedido2;
       this.c7DescPerCent = c7DescPerCent;
       this.c7PerCentFlete = c7PerCentFlete;
       this.c7Plazo = c7Plazo;
       this.c7Guia1 = c7Guia1;
       this.c7Guia2 = c7Guia2;
       this.c7FechaGuia = c7FechaGuia;
       this.c7MontoFlete = c7MontoFlete;
       this.c7ReconociFlete = c7ReconociFlete;
       this.c7Descuento = c7Descuento;
       this.c7MontoAjuste = c7MontoAjuste;
       this.c7Ivm = c7Ivm;
       this.c7Anticipo = c7Anticipo;
       this.c7IvmAnt = c7IvmAnt;
       this.c7CambioMoneda = c7CambioMoneda;
       this.c7Status = c7Status;
       this.inv08Dats = inv08Dats;
    }
    */
    
    public Inv07Dat(String c7Factura, Date c7Fecha, String c7ClienteEspecial, String c7CodigoCliente, String c7RazonSocial, String c7Rif, String c7Nit, String c7Ncf, String c7RetiradoPlanta, String c7DirFiscal1, String c7DirFiscal2, String c7DirFiscal3, String c7Entrega1, String c7Entrega2, String c7Entrega3, String c7Entrega4, String c7Orden1, String c7Orden2, String c7Financiar, String c7CondicionesPago, String c7Vendedor, String c7Nombre, String c7Zona, String c7OrdenCompra1, String c7OrdenCompra2, String c7Pedido1, String c7Pedido2, BigDecimal c7DescPerCent, BigDecimal c7PerCentFlete, Short c7Plazo, String c7Guia1, String c7Guia2, Date c7FechaGuia, BigDecimal c7MontoFlete, BigDecimal c7MontoAjuste, BigDecimal c7ReconociFlete, BigDecimal c7Descuento, BigDecimal c7Ivm, BigDecimal c7Anticipo, BigDecimal c7IvmAnt, BigDecimal c7CambioMoneda, String c7Nc, String c7Status, Set inv08Dats) {
        this.c7Factura = c7Factura;
        this.c7Fecha = c7Fecha;
        this.c7ClienteEspecial = c7ClienteEspecial;
        this.c7CodigoCliente = c7CodigoCliente;
        this.c7RazonSocial = c7RazonSocial;
        this.c7Rif = c7Rif;
        this.c7Nit = c7Nit;
        this.c7Ncf = c7Ncf;
        this.c7RetiradoPlanta = c7RetiradoPlanta;
        this.c7DirFiscal1 = c7DirFiscal1;
        this.c7DirFiscal2 = c7DirFiscal2;
        this.c7DirFiscal3 = c7DirFiscal3;
        this.c7Entrega1 = c7Entrega1;
        this.c7Entrega2 = c7Entrega2;
        this.c7Entrega3 = c7Entrega3;
        this.c7Entrega4 = c7Entrega4;
        this.c7Orden1 = c7Orden1;
        this.c7Orden2 = c7Orden2;
        this.c7Financiar = c7Financiar;
        this.c7CondicionesPago = c7CondicionesPago;
        this.c7Vendedor = c7Vendedor;
        this.c7Nombre = c7Nombre;
        this.c7Zona = c7Zona;
        this.c7OrdenCompra1 = c7OrdenCompra1;
        this.c7OrdenCompra2 = c7OrdenCompra2;
        this.c7Pedido1 = c7Pedido1;
        this.c7Pedido2 = c7Pedido2;
        this.c7DescPerCent = c7DescPerCent;
        this.c7PerCentFlete = c7PerCentFlete;
        this.c7Plazo = c7Plazo;
        this.c7Guia1 = c7Guia1;
        this.c7Guia2 = c7Guia2;
        this.c7FechaGuia = c7FechaGuia;
        this.c7MontoFlete = c7MontoFlete;
        this.c7MontoAjuste = c7MontoAjuste;
        this.c7ReconociFlete = c7ReconociFlete;
        this.c7Descuento = c7Descuento;
        this.c7Ivm = c7Ivm;
        this.c7Anticipo = c7Anticipo;
        this.c7IvmAnt = c7IvmAnt;
        this.c7CambioMoneda = c7CambioMoneda;
        this.c7Nc = c7Nc;
        this.c7Status = c7Status;
        this.inv08Dats = inv08Dats;
    }

    //--------------------------------------------------------------------------
    // * Estructura  utilizada para controlar los next-nro-factura, next-ncf. 
    //--------------------------------------------------------------------------
    public Inv07Dat(String c7Factura, String c7Ncf) {
        this.c7Factura = c7Factura;
        this.c7Ncf = c7Ncf;
    }

    //--------------------------------------------------------------------------
    // * Estructura utilizada para obtener los totales de la Factura. 
    // -------------------------------------------------------------------------
    public Inv07Dat(BigDecimal montoFactura, BigDecimal sumPesoGuia, BigDecimal sumFlete, BigDecimal sumAjuste, BigDecimal subTotal, BigDecimal depGarantia, BigDecimal totalFactura) {
        this.montoFactura = montoFactura;
        this.sumPesoGuia = sumPesoGuia;
        this.sumFlete = sumFlete;
        this.sumAjuste = sumAjuste;
        this.subTotal = subTotal;
        this.depGarantia = depGarantia;
        this.totalFactura = totalFactura;
    }
    
    public String getC7Factura() {
        return this.c7Factura;
    }
    
    public void setC7Factura(String c7Factura) {
        this.c7Factura = c7Factura;
    }
    public Date getC7Fecha() {
        return this.c7Fecha;
    }
    
    public void setC7Fecha(Date c7Fecha) {
        this.c7Fecha = c7Fecha;
    }
    public String getC7ClienteEspecial() {
        return this.c7ClienteEspecial;
    }
    
    public void setC7ClienteEspecial(String c7ClienteEspecial) {
        this.c7ClienteEspecial = c7ClienteEspecial;
    }
    public String getC7CodigoCliente() {
        return this.c7CodigoCliente;
    }
    
    public void setC7CodigoCliente(String c7CodigoCliente) {
        this.c7CodigoCliente = c7CodigoCliente;
    }
    public String getC7RazonSocial() {
        return this.c7RazonSocial;
    }
    
    public void setC7RazonSocial(String c7RazonSocial) {
        this.c7RazonSocial = c7RazonSocial;
    }
    public String getC7Rif() {
        return this.c7Rif;
    }
    
    public void setC7Rif(String c7Rif) {
        this.c7Rif = c7Rif;
    }
    public String getC7Nit() {
        return this.c7Nit;
    }
    
    public void setC7Nit(String c7Nit) {
        this.c7Nit = c7Nit;
    }
    public String getC7Ncf() {
        return this.c7Ncf;
    }
    
    public void setC7Ncf(String c7Ncf) {
        this.c7Ncf = c7Ncf;
    }
    public String getC7RetiradoPlanta() {
        return this.c7RetiradoPlanta;
    }
    
    public void setC7RetiradoPlanta(String c7RetiradoPlanta) {
        this.c7RetiradoPlanta = c7RetiradoPlanta;
    }
    public String getC7DirFiscal1() {
        return this.c7DirFiscal1;
    }
    
    public void setC7DirFiscal1(String c7DirFiscal1) {
        this.c7DirFiscal1 = c7DirFiscal1;
    }
    public String getC7DirFiscal2() {
        return this.c7DirFiscal2;
    }
    
    public void setC7DirFiscal2(String c7DirFiscal2) {
        this.c7DirFiscal2 = c7DirFiscal2;
    }
    public String getC7DirFiscal3() {
        return this.c7DirFiscal3;
    }
    
    public void setC7DirFiscal3(String c7DirFiscal3) {
        this.c7DirFiscal3 = c7DirFiscal3;
    }
    public String getC7Entrega1() {
        return this.c7Entrega1;
    }
    
    public void setC7Entrega1(String c7Entrega1) {
        this.c7Entrega1 = c7Entrega1;
    }
    public String getC7Entrega2() {
        return this.c7Entrega2;
    }
    
    public void setC7Entrega2(String c7Entrega2) {
        this.c7Entrega2 = c7Entrega2;
    }
    public String getC7Entrega3() {
        return this.c7Entrega3;
    }
    
    public void setC7Entrega3(String c7Entrega3) {
        this.c7Entrega3 = c7Entrega3;
    }
    public String getC7Entrega4() {
        return this.c7Entrega4;
    }
    
    public void setC7Entrega4(String c7Entrega4) {
        this.c7Entrega4 = c7Entrega4;
    }
    public String getC7Orden1() {
        return this.c7Orden1;
    }
    
    public void setC7Orden1(String c7Orden1) {
        this.c7Orden1 = c7Orden1;
    }
    public String getC7Orden2() {
        return this.c7Orden2;
    }
    
    public void setC7Orden2(String c7Orden2) {
        this.c7Orden2 = c7Orden2;
    }
    public String getC7Financiar() {
        return this.c7Financiar;
    }
    
    public void setC7Financiar(String c7Financiar) {
        this.c7Financiar = c7Financiar;
    }
    public String getC7CondicionesPago() {
        return this.c7CondicionesPago;
    }
    
    public void setC7CondicionesPago(String c7CondicionesPago) {
        this.c7CondicionesPago = c7CondicionesPago;
    }
    public String getC7Vendedor() {
        return this.c7Vendedor;
    }
    
    public void setC7Vendedor(String c7Vendedor) {
        this.c7Vendedor = c7Vendedor;
    }
    public String getC7Nombre() {
        return this.c7Nombre;
    }
    
    public void setC7Nombre(String c7Nombre) {
        this.c7Nombre = c7Nombre;
    }
    public String getC7Zona() {
        return this.c7Zona;
    }
    
    public void setC7Zona(String c7Zona) {
        this.c7Zona = c7Zona;
    }
    public String getC7OrdenCompra1() {
        return this.c7OrdenCompra1;
    }
    
    public void setC7OrdenCompra1(String c7OrdenCompra1) {
        this.c7OrdenCompra1 = c7OrdenCompra1;
    }
    public String getC7OrdenCompra2() {
        return this.c7OrdenCompra2;
    }
    
    public void setC7OrdenCompra2(String c7OrdenCompra2) {
        this.c7OrdenCompra2 = c7OrdenCompra2;
    }
    public String getC7Pedido1() {
        return this.c7Pedido1;
    }
    
    public void setC7Pedido1(String c7Pedido1) {
        this.c7Pedido1 = c7Pedido1;
    }
    public String getC7Pedido2() {
        return this.c7Pedido2;
    }
    
    public void setC7Pedido2(String c7Pedido2) {
        this.c7Pedido2 = c7Pedido2;
    }
    public BigDecimal getC7DescPerCent() {
        return this.c7DescPerCent;
    }
    
    public void setC7DescPerCent(BigDecimal c7DescPerCent) {
        this.c7DescPerCent = c7DescPerCent;
    }

    public BigDecimal getC7PerCentFlete() {
        return c7PerCentFlete;
    }

    public void setC7PerCentFlete(BigDecimal c7PerCentFlete) {
        this.c7PerCentFlete = c7PerCentFlete;
    }
    
    public Short getC7Plazo() {
        return this.c7Plazo;
    }
    
    public void setC7Plazo(Short c7Plazo) {
        this.c7Plazo = c7Plazo;
    }
    public String getC7Guia1() {
        return this.c7Guia1;
    }
    
    public void setC7Guia1(String c7Guia1) {
        this.c7Guia1 = c7Guia1;
    }
    public String getC7Guia2() {
        return this.c7Guia2;
    }
    
    public void setC7Guia2(String c7Guia2) {
        this.c7Guia2 = c7Guia2;
    }
    public Date getC7FechaGuia() {
        return this.c7FechaGuia;
    }
    
    public void setC7FechaGuia(Date c7FechaGuia) {
        this.c7FechaGuia = c7FechaGuia;
    }

    public BigDecimal getC7MontoFlete() {
        return c7MontoFlete;
    }

    public void setC7MontoFlete(BigDecimal c7MontoFlete) {
        this.c7MontoFlete = c7MontoFlete;
    }

    public BigDecimal getC7MontoAjuste() {
        return c7MontoAjuste;
    }

    public void setC7MontoAjuste(BigDecimal c7MontoAjuste) {
        this.c7MontoAjuste = c7MontoAjuste;
    }
    
    public BigDecimal getC7ReconociFlete() {
        return this.c7ReconociFlete;
    }
    
    public void setC7ReconociFlete(BigDecimal c7ReconociFlete) {
        this.c7ReconociFlete = c7ReconociFlete;
    }
    public BigDecimal getC7Descuento() {
        return this.c7Descuento;
    }
    
    public void setC7Descuento(BigDecimal c7Descuento) {
        this.c7Descuento = c7Descuento;
    }
    public BigDecimal getC7Ivm() {
        return this.c7Ivm;
    }
    
    public void setC7Ivm(BigDecimal c7Ivm) {
        this.c7Ivm = c7Ivm;
    }
    public BigDecimal getC7Anticipo() {
        return this.c7Anticipo;
    }
    
    public void setC7Anticipo(BigDecimal c7Anticipo) {
        this.c7Anticipo = c7Anticipo;
    }
    public BigDecimal getC7IvmAnt() {
        return this.c7IvmAnt;
    }
    
    public void setC7IvmAnt(BigDecimal c7IvmAnt) {
        this.c7IvmAnt = c7IvmAnt;
    }
    public BigDecimal getC7CambioMoneda() {
        return this.c7CambioMoneda;
    }
    
    public void setC7CambioMoneda(BigDecimal c7CambioMoneda) {
        this.c7CambioMoneda = c7CambioMoneda;
    }

    public String getC7Nc() {
        return c7Nc;
    }

    public void setC7Nc(String c7Nc) {
        this.c7Nc = c7Nc;
    }
    
    public String getC7Status() {
        return this.c7Status;
    }
    
    public void setC7Status(String c7Status) {
        this.c7Status = c7Status;
    }
    public Set getInv08Dats() {
        return this.inv08Dats;
    }
    
    public void setInv08Dats(Set inv08Dats) {
        this.inv08Dats = inv08Dats;
    }

    public BigDecimal getMontoFactura() {
        return montoFactura;
    }

    public void setMontoFactura(BigDecimal montoFactura) {
        this.montoFactura = montoFactura;
    }

    public BigDecimal getSumPesoGuia() {
        return sumPesoGuia;
    }

    public void setSumPesoGuia(BigDecimal sumPesoGuia) {
        this.sumPesoGuia = sumPesoGuia;
    }

    public BigDecimal getSumFlete() {
        return sumFlete;
    }

    public void setSumFlete(BigDecimal sumFlete) {
        this.sumFlete = sumFlete;
    }

    public BigDecimal getSumAjuste() {
        return sumAjuste;
    }

    public void setSumAjuste(BigDecimal sumAjuste) {
        this.sumAjuste = sumAjuste;
    }

    public BigDecimal getSubTotal() {
        return subTotal;
    }

    public void setSubTotal(BigDecimal subTotal) {
        this.subTotal = subTotal;
    }

    public BigDecimal getDepGarantia() {
        return depGarantia;
    }

    public void setDepGarantia(BigDecimal depGarantia) {
        this.depGarantia = depGarantia;
    }
    
    public BigDecimal getTotalFactura() {
        return totalFactura;
    }

    public void setTotalFactura(BigDecimal totalFactura) {
        this.totalFactura = totalFactura;
    }

}


