package bean.entidad;
// Generated 04-sep-2014 15:29:48 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Inv02DatId generated by hbm2java
 */
public class Inv02DatId  implements java.io.Serializable {


     private String c2Codigo;
     private Date c2Fecha;

    public Inv02DatId() {
    }

    public Inv02DatId(String c2Codigo, Date c2Fecha) {
       this.c2Codigo = c2Codigo;
       this.c2Fecha = c2Fecha;
    }
   
    public String getC2Codigo() {
        return this.c2Codigo;
    }
    
    public void setC2Codigo(String c2Codigo) {
        this.c2Codigo = c2Codigo;
    }
    public Date getC2Fecha() {
        return this.c2Fecha;
    }
    
    public void setC2Fecha(Date c2Fecha) {
        this.c2Fecha = c2Fecha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Inv02DatId) ) return false;
		 Inv02DatId castOther = ( Inv02DatId ) other; 
         
		 return ( (this.getC2Codigo()==castOther.getC2Codigo()) || ( this.getC2Codigo()!=null && castOther.getC2Codigo()!=null && this.getC2Codigo().equals(castOther.getC2Codigo()) ) )
 && ( (this.getC2Fecha()==castOther.getC2Fecha()) || ( this.getC2Fecha()!=null && castOther.getC2Fecha()!=null && this.getC2Fecha().equals(castOther.getC2Fecha()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getC2Codigo() == null ? 0 : this.getC2Codigo().hashCode() );
         result = 37 * result + ( getC2Fecha() == null ? 0 : this.getC2Fecha().hashCode() );
         return result;
   }   


}


