package bean.entidad;
// Generated 04-sep-2014 15:29:48 by Hibernate Tools 3.6.0



/**
 * Inv06Dat generated by hbm2java
 */
public class Inv06Dat  implements java.io.Serializable {


     private String c6Tipo;
     private String c6Descripcion;
     private String c6Ubicacion;
     private String c6Fxunidad;
     private String c6Fxpeso;
     private String c6Lxunidad;
     private String c6Lxpeso;

    public Inv06Dat() {
    }

	
    public Inv06Dat(String c6Tipo) {
        this.c6Tipo = c6Tipo;
    }
    public Inv06Dat(String c6Tipo, String c6Descripcion, String c6Ubicacion, String c6Fxunidad, String c6Fxpeso, String c6Lxunidad, String c6Lxpeso) {
       this.c6Tipo = c6Tipo;
       this.c6Descripcion = c6Descripcion;
       this.c6Ubicacion = c6Ubicacion;
       this.c6Fxunidad = c6Fxunidad;
       this.c6Fxpeso = c6Fxpeso;
       this.c6Lxunidad = c6Lxunidad;
       this.c6Lxpeso = c6Lxpeso;
    }
   
    public String getC6Tipo() {
        return this.c6Tipo;
    }
    
    public void setC6Tipo(String c6Tipo) {
        this.c6Tipo = c6Tipo;
    }
    public String getC6Descripcion() {
        return this.c6Descripcion;
    }
    
    public void setC6Descripcion(String c6Descripcion) {
        this.c6Descripcion = c6Descripcion;
    }
    public String getC6Ubicacion() {
        return this.c6Ubicacion;
    }
    
    public void setC6Ubicacion(String c6Ubicacion) {
        this.c6Ubicacion = c6Ubicacion;
    }
    public String getC6Fxunidad() {
        return this.c6Fxunidad;
    }
    
    public void setC6Fxunidad(String c6Fxunidad) {
        this.c6Fxunidad = c6Fxunidad;
    }
    public String getC6Fxpeso() {
        return this.c6Fxpeso;
    }
    
    public void setC6Fxpeso(String c6Fxpeso) {
        this.c6Fxpeso = c6Fxpeso;
    }
    public String getC6Lxunidad() {
        return this.c6Lxunidad;
    }
    
    public void setC6Lxunidad(String c6Lxunidad) {
        this.c6Lxunidad = c6Lxunidad;
    }
    public String getC6Lxpeso() {
        return this.c6Lxpeso;
    }
    
    public void setC6Lxpeso(String c6Lxpeso) {
        this.c6Lxpeso = c6Lxpeso;
    }




}


