package bean.entidad;
// Generated 05-sep-2014 14:23:58 by Hibernate Tools 3.6.0



/**
 * Inv04DatId generated by hbm2java
 */
public class Inv04DatId  implements java.io.Serializable {


     private String c4Orden;
     private String c4Codigo;

    public Inv04DatId() {
    }

    public Inv04DatId(String c4Orden, String c4Codigo) {
       this.c4Orden = c4Orden;
       this.c4Codigo = c4Codigo;
    }
   
    public String getC4Orden() {
        return this.c4Orden;
    }
    
    public void setC4Orden(String c4Orden) {
        this.c4Orden = c4Orden;
    }
    public String getC4Codigo() {
        return this.c4Codigo;
    }
    
    public void setC4Codigo(String c4Codigo) {
        this.c4Codigo = c4Codigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Inv04DatId) ) return false;
		 Inv04DatId castOther = ( Inv04DatId ) other; 
         
		 return ( (this.getC4Orden()==castOther.getC4Orden()) || ( this.getC4Orden()!=null && castOther.getC4Orden()!=null && this.getC4Orden().equals(castOther.getC4Orden()) ) )
 && ( (this.getC4Codigo()==castOther.getC4Codigo()) || ( this.getC4Codigo()!=null && castOther.getC4Codigo()!=null && this.getC4Codigo().equals(castOther.getC4Codigo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getC4Orden() == null ? 0 : this.getC4Orden().hashCode() );
         result = 37 * result + ( getC4Codigo() == null ? 0 : this.getC4Codigo().hashCode() );
         return result;
   }   


}


