package bean.entidad;
// Generated 27-ago-2014 12:01:47 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Vend01Dat generated by hbm2java
 */
public class Vend01Dat  implements java.io.Serializable {


     private String c1CodVendedor;
     private String c1Ci;
     private String c1NombreVend;
     private String c1Direccion1;
     private String c1Direccion2;
     private String c1Telefono;
     private String c1Celular;
     private BigDecimal c1LimitCredito;
     private String c1CodRuta;
     private String c1Zona;
     private String c1Clave;

    public Vend01Dat() {
    }

	
    public Vend01Dat(String c1CodVendedor) {
        this.c1CodVendedor = c1CodVendedor;
    }
    public Vend01Dat(String c1CodVendedor, String c1Ci, String c1NombreVend, String c1Direccion1, String c1Direccion2, String c1Telefono, String c1Celular, BigDecimal c1LimitCredito, String c1CodRuta, String c1Zona, String c1Clave) {
       this.c1CodVendedor = c1CodVendedor;
       this.c1Ci = c1Ci;
       this.c1NombreVend = c1NombreVend;
       this.c1Direccion1 = c1Direccion1;
       this.c1Direccion2 = c1Direccion2;
       this.c1Telefono = c1Telefono;
       this.c1Celular = c1Celular;
       this.c1LimitCredito = c1LimitCredito;
       this.c1CodRuta = c1CodRuta;
       this.c1Zona = c1Zona;
       this.c1Clave = c1Clave;
    }
   
    public String getC1CodVendedor() {
        return this.c1CodVendedor;
    }
    
    public void setC1CodVendedor(String c1CodVendedor) {
        this.c1CodVendedor = c1CodVendedor;
    }
    public String getC1Ci() {
        return this.c1Ci;
    }
    
    public void setC1Ci(String c1Ci) {
        this.c1Ci = c1Ci;
    }
    public String getC1NombreVend() {
        return this.c1NombreVend;
    }
    
    public void setC1NombreVend(String c1NombreVend) {
        this.c1NombreVend = c1NombreVend;
    }
    public String getC1Direccion1() {
        return this.c1Direccion1;
    }
    
    public void setC1Direccion1(String c1Direccion1) {
        this.c1Direccion1 = c1Direccion1;
    }
    public String getC1Direccion2() {
        return this.c1Direccion2;
    }
    
    public void setC1Direccion2(String c1Direccion2) {
        this.c1Direccion2 = c1Direccion2;
    }
    public String getC1Telefono() {
        return this.c1Telefono;
    }
    
    public void setC1Telefono(String c1Telefono) {
        this.c1Telefono = c1Telefono;
    }
    public String getC1Celular() {
        return this.c1Celular;
    }
    
    public void setC1Celular(String c1Celular) {
        this.c1Celular = c1Celular;
    }
    public BigDecimal getC1LimitCredito() {
        return this.c1LimitCredito;
    }
    
    public void setC1LimitCredito(BigDecimal c1LimitCredito) {
        this.c1LimitCredito = c1LimitCredito;
    }
    public String getC1CodRuta() {
        return this.c1CodRuta;
    }
    
    public void setC1CodRuta(String c1CodRuta) {
        this.c1CodRuta = c1CodRuta;
    }
    public String getC1Zona() {
        return this.c1Zona;
    }
    
    public void setC1Zona(String c1Zona) {
        this.c1Zona = c1Zona;
    }
    public String getC1Clave() {
        return this.c1Clave;
    }
    
    public void setC1Clave(String c1Clave) {
        this.c1Clave = c1Clave;
    }




}


